from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.common.by import By
from Test_data.data import Nivetha_data
from time import sleep
from Test_locators.locators import Nivetha_locators
from selenium.webdriver.support.ui import Select

class Nivetha:
    

    def __init__(self,url):
        self.driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()))
        self.driver.maximize_window()
        self.driver.get(url)   
    
    def register(self):
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().reg_sl).click()
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gender_l).click()
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().firstname_l).send_keys(Nivetha_data().firstname)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().lastname_l).send_keys(Nivetha_data().lastname)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dob_l).send_keys(Nivetha_data().dob1)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dob_2).send_keys(Nivetha_data().dob2)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dob_3).send_keys(Nivetha_data().dob3)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().email_l).send_keys(Nivetha_data().email)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().companyname_l).send_keys(Nivetha_data().companyname)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().password_l).send_keys(Nivetha_data().password)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().confirmp_l).send_keys(Nivetha_data().confirmpassword)
       self.driver.implicitly_wait(10)
       self.driver.find_element(by=By.XPATH, value=Nivetha_locators().final_reg).click()

    def login(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().login_sl).click()
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().emaillog_l).send_keys(Nivetha_data().email)
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().passwordlog_l).send_keys(Nivetha_data().password)
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().login_l).click()
        sleep(3)
    def computers(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().computers_l).click()
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().desktop_l).click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(by=By.XPATH , value=Nivetha_locators().dpp_l).click()
       
    def select_ram(self):
        sleep(4)
        print('Method - select_ram')
        ram = self.driver.find_element(by=By.NAME, value='product_attribute_2')
        ram_dropdown = Select(ram)
        ram_dropdown.select_by_visible_text('2 GB')
        sleep(4)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().hdd_l).click()
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dproduct_1).click()
        self.driver.implicitly_wait(5)      
        self.driver.back()
        sleep(5) 
        self.driver.find_element(by=By.XPATH , value=Nivetha_locators().dpp_2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dproduct_2).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(5)
        self.driver.find_element(by=By.XPATH , value=Nivetha_locators().dpp_3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dproduct_3).click()
        sleep(5)
        self.driver.back()
    def notebook(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().notebook_l).click()
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_1).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_2).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_3).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb4).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_4).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb5).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_5).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nb6).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().nbpro_6).click()
        self.driver.back()
        sleep(5)

    def software(self):
        sleep(5)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().softwarel).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().computers_l).click()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().software_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().software2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().sproduct_2).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().software3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().sproduct_3).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)

    def electronics(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().electronics_l).click()
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cp1l).click()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cp1).click()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cpl_1b).click()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cpl_1r).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cp3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cpl_3).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cellphone_l).click()
        # self.driver.implicitly_wait(5)
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell1).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell1_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell2).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell2_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell3).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cell3_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().others_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().others1).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().other1_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().others2).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().other2_l).click()
        # self.driver.implicitly_wait(5)
        # self.driver.back()
        # sleep(3)
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().others3).click()
        # self.driver.find_element(by=By.XPATH, value=Nivetha_locators().other3_l).click()
        # sleep(5)

    def select_apparel(self):
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().apparel_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoes_l).click()
        self.driver.implicitly_wait(5)
        sleep(4)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe1).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        apparel = self.driver.find_element(by=By.NAME, value='product_attribute_9')
        apparel_dropdown = Select(apparel)
        apparel_dropdown.select_by_visible_text('10')
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe1_l).click()
        sleep(3)
        self.driver.back()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe2).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        apparel = self.driver.find_element(by=By.NAME, value='product_attribute_6')
        apparel_dropdown = Select(apparel)
        apparel_dropdown.select_by_visible_text('10')
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().print).click()
        self.driver.find_element(by=By.XPATH , value=Nivetha_locators().colour_l).send_keys(Nivetha_data().colour)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe2_l).click()
        sleep(3)
        self.driver.back()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().shoe3_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().clothing_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().text).send_keys("hello people")
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth1_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth2_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth3).click()
        apparel = self.driver.find_element(by=By.NAME, value='product_attribute_11')
        apparel_dropdown = Select(apparel)
        apparel_dropdown.select_by_value('30')
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth3_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth4).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().cloth4_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().accessories_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().acc1).click()
        apparel = self.driver.find_element(by=By.NAME, value='product_attribute_13')
        apparel_dropdown = Select(apparel)
        apparel_dropdown.select_by_value('36')
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().accessory1).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().acc2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().accessory2).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().acc3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().accessory3).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
    def digitaldownloads(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().ddownloads_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd1_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd2_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().dd3_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
    def books(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().books_l).click()
        self.driver.implicitly_wait(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book1_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book2_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().book3_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
    def jewelry(self): 
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewelry_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().startdate_l).send_keys(Nivetha_data().startdate)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().enddate_l).send_keys(Nivetha_data().enddate)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel1_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel2_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().jewel3_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
    def giftcard(self):
        sleep(5)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().giftcard_l).click()
        self.driver.implicitly_wait(5)
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift1).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().rn_l).send_keys(Nivetha_data().rn)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().re_l).send_keys(Nivetha_data().re)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().urn_l).send_keys(Nivetha_data().urn)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().ure_l).send_keys(Nivetha_data().ure)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().message_l).send_keys(Nivetha_data().message)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift1_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift2).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().rname_l).send_keys(Nivetha_data().rname)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().urname_l).send_keys(Nivetha_data().urname)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().message_loc).send_keys(Nivetha_data().messagee)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift2_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift3).click()
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().rec_l).send_keys(Nivetha_data().rec)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().yourn_l).send_keys(Nivetha_data().yourn)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().mess_l).send_keys(Nivetha_data().mess)
        self.driver.find_element(by=By.XPATH, value=Nivetha_locators().gift3_l).click()
        self.driver.implicitly_wait(5)
        self.driver.back()
        sleep(3)
    
url = "https://demo.nopcommerce.com/"
n = Nivetha(url)
n.register()
n.login()
n.computers()
n.select_ram()
n.notebook()
n.software()
n.electronics()
n.select_apparel()
n.digitaldownloads()
n.books()
n.jewelry()
n.giftcard()

